# Generated by Django 2.2.12 on 2022-02-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_in', models.URLField()),
                ('accessed', models.DateTimeField(verbose_name='date accessed')),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
