# Generated by Django 2.2.12 on 2022-02-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpm', '0002_auto_20220208_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlin',
            name='accessed',
        ),
    ]
