# Generated by Django 2.2.12 on 2022-02-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpm', '0003_remove_urlin_accessed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlIn',
            new_name='Url',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='url_in',
            new_name='url_text',
        ),
    ]
